title: Miguel L贸pez | Aerospace Systems & Software
description: Aerospace Engineer specializing in MBSE, Critical Flight Software (C++, Rust), and Space Systems.
url: "https://miguelcllopez.github.io/" # O tu url de github.io
author:
  name: Miguel L贸pez Cordero
  email: contacto@miguelcllopez.com

# Configuraci贸n de Construcci贸n
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
