title: Miguel López | Aerospace Systems & Software
email: miguelcllopez@gmail.com
description: >- # El ">-" permite escribir en varias líneas
  Aerospace Engineer specializing in MBSE, Critical Flight Software (C++, Rust), and Space Systems.
baseurl: "" 
url: "https://miguelcllopez.github.io/" 
author: Miguel López Cordero

# Configuración de Construcción
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
