title: Miguel López | Ingeniería Aeroespacial
email: contacto@miguelcllopez.com
description: >- # Descripción para SEO
  Estudiante de Ingeniería Aeroespacial. Proyectos de simulación numérica,
  dinámica de fluidos (CFD) y diseño estructural.
baseurl: "" # Dejar vacío para usuario.github.io
url: "https://miguelcllopez.github.io"
twitter_username: 
github_username: miguelcllopez

# Configuración de Construcción
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
